### ISSUE TITLE
New Droplets dont have IP address immediatly, so the info command fails

### ISSUE THREAD

**Issue by petems** [pearkes/tugboat#198]
```
$ bundle exec tugboat create foo && bundle exec tugboat wait foo && bundle exec tugboat ssh foo
Queueing creation of droplet 'foo'...Droplet created!
Droplet fuzzy name provided. Finding droplet ID.../Users/petersouter/projects/tugboat/lib/tugboat/middleware/find_droplet.rb:103:in `call': undefined method `ip_address' for nil:NilClass (NoMethodError)
	from /Users/petersouter/projects/tugboat/lib/tugboat/middleware/inject_client.rb:27:in `call'
	from /Users/petersouter/projects/tugboat/lib/tugboat/middleware/check_configuration.rb:19:in `call'
	from /Users/petersouter/projects/tugboat/lib/tugboat/middleware/inject_configuration.rb:10:in `call'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
	from /Users/petersouter/projects/tugboat/lib/tugboat/cli.rb:528:in `wait'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Users/petersouter/projects/tugboat/bin/tugboat:10:in `<top (required)>'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/bin/tugboat:23:in `load'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/bin/tugboat:23:in `<main>'
```

Need to have it take nil as an empty string or something

**Comment by petems** [comment]
Fixed by e3a69d2b548f8b4b47a538a2605928db23490bc7
